<%@ Page Title="" Language="C#" MasterPageFile="~/masterpage.Master" AutoEventWireup="true" CodeBehind="UpDelIns.aspx.cs" Inherits="MidtermProject1.UpDelIns" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-left: 0;
        }
        .auto-style2 {
            width: 100%;
        }
    </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id" DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="985px">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id" />
            <asp:BoundField DataField="Fname" HeaderText="Fname" SortExpression="Fname" />
            <asp:BoundField DataField="Lname" HeaderText="Lname" SortExpression="Lname" />
            <asp:BoundField DataField="Qual" HeaderText="Qual" SortExpression="Qual" />
            <asp:BoundField DataField="Course" HeaderText="Course" SortExpression="Course" />
        </Columns>
    </asp:GridView>
    <br />
    <br />
    <table class="auto-style2">
        <tr>
            <td>id</td>
            <td>
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Fname</td>
            <td>
    <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Lname</td>
            <td><asp:TextBox ID="TextBox3" runat="server" CssClass="auto-style1"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Qual</td>
            <td>
    <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Course</td>
            <td>
    <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
            </td>
        </tr>
    </table>
    <br />
&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert" Width="239px" />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        SelectCommand="SELECT * FROM [updelete]"
        UpdateCommand="UPDATE [updelete] Set [Fname]=@Fname , [Lname]=@Lname , [Qual]=@Qual , [Course]=@Course where [id]=@id"
        DeleteCommand="DELETE from [updelete] where [id]=@id"
        >

    </asp:SqlDataSource>
    
</asp:Content>
